config/routes.rb
Rails.application.routes.draw do
  resources :csv_files, only: [:index, :show, :create] do
    get :check, on: :member
  end
  root "csv_files#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/csv_upload.rb
class CsvUpload < ApplicationRecord
  has_one_attached :csvfile
  has_many :user_data, dependent: :destroy
  has_many :error_rows, dependent: :destroy

  def parse_csvfile
    logger.info("CSVFILE:" + csvfile.inspect)
    csvfile.blob.open(tmpdir: Rails.root.join("tmp")) do |file|
      CsvParser.parse(file.path, self)
    end
  end
end

app/models/error_row.rb
class ErrorRow < ApplicationRecord
  belongs_to :csv_upload
end

app/models/user_datum.rb
require_relative '../validators/phone_validator'

class UserDatum < ApplicationRecord
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_NAME_REGEX = /\A[A-Za-z]{2,}\z/
  belongs_to :csv_upload, required: false
  
  validate :names_validation
  validates_with PhoneValidator
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates :first, length: { minimum: 2 }, allow_blank: true, allow_nil: true, format: {with: VALID_NAME_REGEX }
  validates :last, length: { minimum: 2 }, allow_blank: true, allow_nil: true, format: {with: VALID_NAME_REGEX }

  def names_validation
    if !last.to_s.strip.empty? && first.to_s.strip.empty?
      errors.add(:names, "First name required if last name specified")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
  # skip_before_action :verify_authenticity_token
  def index
    @csv_uploads = CsvUpload.all
  end

  def show
    @csv_upload = CsvUpload.find_by_id(params[:id])
  end

  def create
    rec = CsvUpload.find_by_name(params[:info][:name])
    if rec
      rec.email = params[:info][:email]
      rec.csvfile.purge
    else
      rec = CsvUpload.create(upload_params) unless CsvUpload.count > 300
    end
    fil = params[:csvfile]

    logger.info("CSV FILE: #{fil.path}")
    rec.csvfile.attach(io: File.open(fil.path), 
      filename: fil.original_filename, content_type: "text/csv")
    rec.save!
    UploadJob.perform_async({csv_id: rec.id})
    @recid = rec.id
  end

  def check
    rec = CsvUpload.find_by_id(params[:id])
    # make sure db/cache settles down before client renders new data
    # not sure why this is needed but fails without it
    sleep 3 if rec.status == 'success'
    render json:({status: rec.status}.to_json)
  end

  private
  def upload_params
    params.require(:info).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_files_helper.rb
module CsvFilesHelper
end

app/views/csv_files/create.js.erb
console.log("recid", "<%= @recid.to_s %>");

// spinner indicates backend is working
let str = '<img src="' + "<%= image_path('loading.gif')%>" + '"' +
  'width="65" height="65">'; 
$("#loading-container").html(str);

(function poll() {
    setTimeout(function() {
        $.ajax({
            url: "/csv_files/<%= @recid.to_s %>/check/",
            type: "GET",
            success: function(data) {
                console.log("polling", data);
                if (data.status == 'success') {
                  window.location.assign("/csv_files/<%= @recid.to_s %>");
                }
            },
            dataType: "json",
            complete: poll,
            timeout: 10000
        })
    }, 5000);
})();

app/views/csv_files/index.html.erb
<div class="container">
  <h3> CSV Uploads </h3>
  <table class="table csv-upload-table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
      </tr>
    </thead>
    <tbody>
      <% @csv_uploads.each do |rec| %>
      <tr>
        <td><%= link_to rec.name, csv_file_path(rec) %></td>
        <td><%= rec.email %></td>
      </tr>
      <% end %>
    </tbody>
  </table>  
</div>

app/views/csv_files/show.html.erb
<div class="container">

  <h3>CSV Upload: <%= @csv_upload.name %> (<%= @csv_upload.email%>)</h3>

  <table class="table main-table">
    <thead>
      <tr>
        <th scope="col">Row</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
      </tr>
    </thead>
    <tbody>
      <% @csv_upload.user_data.each do |row| %>
      <tr>
        <th scope="row"><%= row.row %></th>
        <td><%= row.first %></td>
        <td><%= row.last %></td>
        <td><%= row.email %></td>
        <td><%= row.phone %></td>
      </tr>
      <% end %>
    </tbody>  
  </table>

  <% unless @csv_upload.error_rows.empty? %>
    <table class="table error-table main-table">
      <thead>
        <tr>
          <th scope="col">Row</th>
          <td> Error </td>
        </tr>    
      </thead>
      <tbody>
        <% @csv_upload.error_rows.each do |erow| %>
          <tr>
          <th scope="col"><%= erow.row %></th>
          <td class='error-message'><%= erow.error_msg %>
        </tr>    
        <% end %>
      </tbody>  
  <% end %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="/">CSV File Uploader</a>
          <form class="form-inline">
            <button class="btn btn-outline-primary" onclick="location.href='/'" type="button">Home</button>
            <span style="padding-left: 10px;">
              <button class="btn btn-outline-success" type="button" 
               data-toggle="modal" data-target="#uploadModal">Upload CSV File</button>
            </span>
          </form>
      </nav>
    </div>
    <%= yield %>

    <div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div id="loading-container"></div>
            <%= form_tag "/csv_files", :multipart => true, :method => :post, :id => 'csv-form', :remote => true do %>
              <div class="form-group">
                <label for="formGroupIdentifier">Identifier</label>
                <input name="info[name]" type="text" class="form-control" id="name" placeholder="Name" 
                minlength='2'
                pattern="[a-zA-Z0-9]\S+" required>
              </div>
              <div class="form-group">
                <label for="userEmail">Email address</label>
                <input name="info[email]" type="email" class="form-control" id="userEmail" aria-describedby="emailHelp" 
                placeholder="Enter email"
                pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required>
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="csvfile">CSV File</label>
                <input name="csvfile" type="file" class="form-control-file" id="csvfile" required>
              </div>
              <button type="submit" class="btn btn-primary submit-btn">Submit</button>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

<script>
  $( document ).ready(function() {
    var group = $('.form-group input');
    var form = $("#csv-form");

    $('#csv-form').bind('ajax:complete', (event,data) => {
      // if(data.success == true) {
        console.log('data for ajax:complete', data);
      // }
    })

  })
</script>


  </body>
</html>